### ISSUE TITLE
Enable simulation experiments to indicate whether basic tasks referenced by repeated tasks should be run individually or not

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#102] opened 2021-02-02 16:17 UTC
As currently structured, the instances of `Task` referenced by repeated tasks are directed nested within SED documents. E.g.,
```xml
<sedML>
    <listOfTask>
        <task id="task1" />
       <repeatedTask id="task2">
           <listOfSubTasks>
               <subTask task="task1" />
           </listOfSubTasks>
      </repeatedTask>
</sedML>
```

I think most investigators would likely interpret the execution to be the following:
1. `Task` `task1` is executed
2. `RepeatedTask` `task2` is executed
     - `Task` `task1` is executed for each iteration of the range of `task2`    

However, some might want this to be interpreted as the following:
1. `RepeatedTask` `task2` is executed
     - `Task` `task1` is executed for each iteration of the range of `task2`    

Currently, it's not possible to indicate whether instances of `Task` referenced by repeated tasks should or shouldn't be executed individually.

This could be resolved in two ways:
- Clearly indicate in the specifications the intended interpretation
- Modify the schema to allow simulation experiments to indicate whether instances of `Task` should be executed individually. 
   - This requires a Boolean attribute to indicate this.

**Comment by luciansmith** [comment] 2021-02-02 17:18
In fact, neither interpretation is correct (if I understand things right).  Instead, the list of tasks merely describes what tasks *can* be run, but does not indicate that any of them should actually *be* run.  To determine what tasks to run, you have to look at the outputs and see what they reference.  If one output requests the output of task1, then you just run task1.  If another output requests the output of task2, you run task2 for that.  I believe that the state should be reset between outputs, though I'm a little iffy on that bit, and we might need more detail in the spec about it.

Overall, you have to build up your simulation in reverse:  you look at the outputs first, then figure out what tasks they need, then figure out what models/simulations you need.  There might be elements in a SED-ML file that never get touched, if there's no output that references it.

**Comment by jonrkarr** [comment] 2021-02-02 17:46
Of course it would be more efficient not to execute tasks that don't contribute to reports or plots. However, its not necessary to do this, and one has to be careful that skipping tasks doesn't affect the tasks which are executed.

I don't see how @luciansmith's interpretation falls from the specifications. From the lens of other workflow languages (which developers are likely more familiar with than SED-ML), I don't think this interpretation is obvious. Furthermore, my reading of the specifications is that it suggests a different interpretation. For example, the overview (1.1 of L1V4), suggests that tasks define the procedure to run on each model (it doesn't say the possible procedures that could be run on each model). Similarly, the tasks are nested under `listOfTasks` not `listOfTaskTypes`. In my opinion, calling them "tasks" suggests they should be executed, not that they could be executed.

One reason that is not obvious that tasks can simply be skipped as a performance optimization is that whether tasks not referenced by outputs are executed can affect the results of the tasks which are referenced by outputs. For example, this can occur with stochastic simulation tools where tasks can change the state of the random number generator. Of course simulation tools which are aware of the implementation of their algorithms could know whether this is relevant to them or not.

If @luciansmith's interpretation is the intended interpretation, I think this this should be clearly stated in the specifications and reinforced with clearer terminology. For example, `Task` could be renamed to `TaskType`. Examples could be added which illustrate skipped tasks.

**Comment by luciansmith** [comment] 2021-02-02 20:13
It goes beyond the RNG--if task1 is (say) a simulation, its model's state will be completely different if it's already been run once before the repeat in task2.  Add to this the fact that SED-ML was created at a time when the community was striving to make XML definitions of everything order-agnostic, this means that this list of tasks:

```
    <listOfTasks>
        <task id="task1" />
        <task id="task2" />
    </listOfTasks>
```

should be identical to this list of tasks:

```
    <listOfTasks>
        <task id="task2" />
        <task id="task1" />
    </listOfTasks>
```

So if both task1 and task2 reference the same model, the only possible way that both lists can be identical is if tasks have an implied state reset between them.

This is, I agree, 100% not covered by the text of the specification.  It's more lore that I've picked up over the years from talking to people who were involved in SED-ML's creation.  This is less than ideal!

I disagree that the word 'task' implies that you must carry out the task.  I mean, I've had a task list posted in my kitchen for over a year with things on it I have yet to do.  I think it's reasonably analogous to a 'function' in a computer program.  The assumption is that you probably wrote the function because you execute it somewhere, but if you never call the function, it's nothing but dead code that someone might use some day.

**Comment by jonrkarr** [comment] 2021-02-02 20:24
This "lore" should to be more explicit.

One thing that SBOL has done to make SBOL easier to evolve is to support recommendations separate from the official specification. This functions similar to PEPs for Python. For SBOL, these are implement as GitHub issues. These are much less formal, and can be voted on and adopted much faster than changes to the official specification, which is much more formal. 

Workflow systems don't function quite like code. Tasks aren't explicitly scheduled in the same manner as code. At least in some systems, tasks are executed unless a dependency isn't met (e.g., because a dependent task failed).

**Comment by luciansmith** [comment] 2021-02-03 00:53
I absolutely agree it should be explicit.

A PEP-like system is definitely a possibility, if we can find the people with the bandwidth to set it up, use it, and advertise it.  (And if we're willing to steal that bandwidth away from other tasks like updating the spec itself.  But maybe it would make that job easier?  I don't know.)

From my fairly shallow investigation of Workflow systems, it looks like they are set up to reproduce concrete procedures on particular architectures.  Which is sort of too bad, because otherwise the goals are similar to SED-ML.  But an investigation of what SED-ML could steal from workflows for level 2 would seem to me to be profitable.

**Comment by jonrkarr** [comment] 2021-04-12 20:46
The resolution is that only tasks that contribute to outputs need to be executed. This will be clarified as part of general discussion about what needs to be executed and what can be skipped.

**Comment by matthiaskoenig** [comment] 2021-04-13 19:01
We will close this with the pull request which updates the specification. I will leave this open so we do not forget to update the specification with the clarification.

**Comment by luciansmith** [comment] 2021-06-09 19:21
Added the following to the listOfTasks description:

"Each task is defined independently of the others: if one task is executed after another, the states of the
models must be completely reset so there’s no cross-contamination of one task to the next. This means
that the tasks are particularly well suited to being executed in parallel, should that be desired.

SED-ML interpreters may choose to execute all the tasks in the list, or they may choose to examine the
list of outputs, and only execute the tasks that are necessary to produce the requested output. This
situation comes up most often when one task is listed as a SubTask of a RepeatedTask: the outputs may
well only require the RepeatedTask to be run, meaning an independent execution of the singular Task
is not necessary, even though it’s on this list."

**Comment by luciansmith** [comment] 2021-06-09 19:22
(Leaving this open for now, but can be closed if we're happy with the text.)

**Comment by jonrkarr** [comment] 2021-06-09 20:03
> "Each task is defined independently of the others:"

I think language could be a source of confusion because repeated tasks are defined as a collection of additional tasks. I suggest rephrasing to clarify that the top-level of tasks should be executed independently (state completely reset as you described).

I would emphasize top level tasks in this sentence below too to avoid confusion with subtasks in repeated tasks which may need to be executed in a specific order.

> This means that the **top level** tasks are well suited to being executed in parallel, should that be desired.

**Comment by luciansmith** [comment] 2021-06-09 21:33
Good suggestions; the new version is now:

"Each top-level task is defined such that its execution is independent of the others: if one task is executed
after another, the states of the models must be completely reset so there’s no cross-contamination of one
task to the next. This means that the top-level tasks are particularly well suited to being executed in
parallel, should that be desired."

**Comment by jonrkarr** [comment] 2021-06-09 21:38
That sounds good to me.

**Comment by fbergmann** [comment] 2021-07-19 14:25
I'm fine with the formulation as well.

**Comment by matthiaskoenig** [comment] 2021-07-19 18:27
Sounds good.

**Closed** 2021-08-03 20:32 UTC
Labels: L1V4, draft fix
